### PR TITLE
reduced logging level to Error

### PR DESCRIPTION
**Pull request by razvangoga**

### CODE REVIEW

**Comment by martin-g** [comment]
ARM64 results:

```
{
  "latencies": {
    "total": 284907093739,
    "mean": 553459,
    "50th": 509426,
    "90th": 737653,
    "95th": 851459,
    "99th": 1180301,
    "max": 289693230,
    "min": 234433
  },
  "bytes_in": {
    "total": 6177300,
    "mean": 12
  },
  "bytes_out": {
    "total": 0,
    "mean": 0
  },
  "earliest": "2020-10-09T11:43:33.23949725Z",
  "latest": "2020-10-09T11:44:03.239480424Z",
  "end": "2020-10-09T11:44:03.239880469Z",
  "duration": 29999983174,
  "wait": 400045,
  "requests": 514775,
  "rate": 17159.176290676674,
  "throughput": 17158.947478843536,
  "success": 1,
  "status_codes": {
    "200": 514775
  },
  "errors": []
}
```

**Comment by martin-g** [comment]
x86_64:

```
{
  "latencies": {
    "total": 294867720396,
    "mean": 829916,
    "50th": 799153,
    "90th": 911629,
    "95th": 992587,
    "99th": 1230521,
    "max": 164654147,
    "min": 666179
  },
  "bytes_in": {
    "total": 4263576,
    "mean": 12
  },
  "bytes_out": {
    "total": 0,
    "mean": 0
  },
  "earliest": "2020-10-09T11:44:30.122067833Z",
  "latest": "2020-10-09T11:45:00.122028277Z",
  "end": "2020-10-09T11:45:00.122750487Z",
  "duration": 29999960444,
  "wait": 722210,
  "requests": 355298,
  "rate": 11843.282282429132,
  "throughput": 11842.997177686822,
  "success": 1,
  "status_codes": {
    "200": 355298
  },
  "errors": []
}
```

**Comment by martin-g** [comment]
Please let me know if you have any optimizations you like to do before updating the blog article with these results!
Many thanks for your help on this !

**Comment by razvangoga** [comment]
hmm.. quite strange that the ARM run is ~50%faster (17k vs 11k)

can you try to rerun them in Release mode *dotnet run --configuration
Release cert_pass*

**Comment by martin-g** [comment]
with `--configuration Release`

x86_64:

```
{
  "latencies": {
    "total": 294910907823,
    "mean": 834548,
    "50th": 802307,
    "90th": 920117,
    "95th": 1006488,
    "99th": 1241834,
    "max": 166066656,
    "min": 673779
  },
  "bytes_in": {
    "total": 4240536,
    "mean": 12
  },
  "bytes_out": {
    "total": 0,
    "mean": 0
  },
  "earliest": "2020-10-09T12:13:22.542742493Z",
  "latest": "2020-10-09T12:13:52.542738571Z",
  "end": "2020-10-09T12:13:52.543492701Z",
  "duration": 29999996078,
  "wait": 754130,
  "requests": 353378,
  "rate": 11779.268206609664,
  "throughput": 11778.972110696359,
  "success": 1,
  "status_codes": {
    "200": 353378
  },
  "errors": []
}
```

arm64:
```
{
  "latencies": {
    "total": 285247355812,
    "mean": 586436,
    "50th": 534488,
    "90th": 806352,
    "95th": 941453,
    "99th": 1353942,
    "max": 291721547,
    "min": 236343
  },
  "bytes_in": {
    "total": 5836896,
    "mean": 12
  },
  "bytes_out": {
    "total": 0,
    "mean": 0
  },
  "earliest": "2020-10-09T12:14:15.36285614Z",
  "latest": "2020-10-09T12:14:45.362850908Z",
  "end": "2020-10-09T12:14:45.363294874Z",
  "duration": 29999994768,
  "wait": 443966,
  "requests": 486408,
  "rate": 16213.602827652332,
  "throughput": 16213.362888214888,
  "success": 1,
  "status_codes": {
    "200": 486408
  },
  "errors": []
}
```

**Comment by razvangoga** [comment]
hmm.. there may be other configurations that will increase the throughput
(like the case was with Tomcat) but I don't know them off the top of my head

in this case i would turn it over to https://twitter.com/davidfowl - he's
the lead from microsoft in charge of all things related to asp.net /
kestrel (the webserver for .netcore)

at this point i would suggest to update the article with these
initial numbers and if there is no feedback from him / MS i can try to
revisit the issue and try to speed it up (but i need to hit the docs for
this)

**Comment by martin-g** [comment]
OK. Thank you!
I hope David or someone else will send a PR with further improvements!

**Pull request merged**
